config/routes.rb
Rails.application.routes.draw do

  resources :gamas
  
  get 'sessions/new'

  get 'users/new'

  get 'users/show'

  root 'static_pages#home'

  match '/join/:id', to: 'gamas#join', via: [:put]
  match '/leave/:id', to: 'gamas#leave', via: [:put]

  get 'play'    => 'static_pages#play'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'lobby'   => 'static_pages#lobby'
  get 'all'     => 'users#all'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'=> 'sessions#destroy'
  resources :users
end

app/controllers/static_pages_controller.rb
=begin
  The Static Pages controller handles all the static webpages that we see
  on the website.
=end

class StaticPagesController < ApplicationController

  # GET /
  def home
  end

  # GET /help
  def help
  end

  # GET /about
  def about
  end

  # GET /lobby
  def lobby
    @user = current_user
  end

  # GET /play
  def play
  end
end

app/views/static_pages/home.html.erb
<div id="col-M">    
  <div class="main-box">
    <div class="main-top"></div>
      <div class="main-filler">
        
        <div class="main-info">
            
          <h1 class="center">The Great War</h1>
            
          <p class="center">
            Welcome to the Great War!          
          </p>
          <div class="clearB" style="height:20px"></div>
          <div class="clearB" style="height:20px"></div>
          <div class="center">
            <% if logged_in? %>
              <%= link_to "Game List", gamas_path, class: "btn btn-lg btn-default" %>
            <% else %>
              <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-default" %>
            <% end %>
          </div>
        </div>
        
      </div>
      <div class="main-footer"></div>
  </div>
  <div class="clearB" style="height:20px"></div>
</div>

app/views/static_pages/lobby.html.erb
<% provide(:title, "Lobby") %>

<div id="col-M">    
  <div class="main-box">
    <div class="main-top"></div>
    <div class="main-filler">
        
      <div class="main-info">
            
        <h1 class="center">Welcome to the Lobby!</h1>
        <div class="clearB" style="height:20px"></div>
        <div class="center" >
          <% if !@user.gama %>
            <%= link_to "Join Game", gamas_path, class: "btn btn-lg btn-default" %>
            <div class="clearB" style="height:10px"></div>
            <%= link_to "Create Game", new_gama_path, class: "btn btn-lg btn-default" %>
          <% else %>
            <%= link_to "Return to Game", "/play", class: "btn btn-lg btn-default" %>
            <div class="clearB" style="height:10px"></div>
            <%= link_to "Leave Game", "/leave/#{@user.gama_id}", class: "btn btn-lg btn-default", method: :put %>
          <% end %>
        </div>
      </div>
      <div class="main-footer"></div>
    </div>
    <div class="clearB" style="height:20px"></div>
  </div>
</div>

app/views/static_pages/play.html.erb
<div id="the-great-war"></div>