config/routes.rb
Rails.application.routes.draw do

  resources :gamas
  
  get 'sessions/new'

  get 'users/new'

  get 'users/show'

  root 'static_pages#home'

  match '/join/:id', to: 'gamas#join', via: [:put]
  match '/leave/:id', to: 'gamas#leave', via: [:put]

  get 'play'    => 'static_pages#play'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'lobby'   => 'static_pages#lobby'
  get 'all'     => 'users#all'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'=> 'sessions#destroy'
  resources :users
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div id="footer-mid">
    <div id="footer-col-L"></div>
    <div id="footer-col-M">
      <div id="foot-title-section">The Great War</div>
      <div id="foot-title-slogan">"For God, for country, and for Yale"</div>
      <div class="foot-contacts">Supreme Leaders: BDMVW</div>
      <div id="foot-disclaimer">Copyright 2012 - ThemeKings.Net"</div>
    </div>
    <div id="footer-col-R"></div>
  </div>
</div>

app/views/layouts/_header.html.erb
  <div id="banner">
  	<div id="banner-L">
      <span class="website-title">
    <%= link_to "The Great War", root_path, id: "logo" %>
      </span>
    	</div>
      <div id="banner-R"></div>
      <div class="clearB"></div>
      <div id="banner-Hnav">
      <ul class="nav">
        <li><%= link_to "Home", root_path %></li>
        <!-- Display Users and dropdown menu if the user is logged in,
        otherwise, we display a Log-in option -->
        <% if logged_in? %>
          <li><%= link_to "Lobby", lobby_path %></li>
          <li><%= link_to "All Games", gamas_path %></li>
          <li><%= link_to "Users", all_path %></li>
          <li class="dropdown">
            <a href="#">Account</a>
            <ul>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        </ul>
      </li>
      <% else %>
      <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    
    <!-- SEO RELATED META TAGS -->
    <meta name="revisit" content="2 days">
    <meta name="robots" content="all, index, follow">
    <meta name="description" content="">
    <meta name="keywords" content="">

    <meta content="english" name="language">
    <meta content="public" http-equiv="cache-control">
    <%= stylesheet_link_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="cnt-box">
      <div id="cnt-top">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      
      <div id="cnt-filler">
	<%= yield %>
      </div>
      <div id="cnt-btm"></div>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>